const languages = {
    en: {
        title: "Advanced Brute Cipher",
        encryptionDecryption: "Encryption and Decryption",
        instructions: "This tool allows you to encrypt and decrypt text using two keys. You can either:",
        instructionItem1: "Remember or note down the two keys (Extra Key 1 and Extra Key 2),",
        instructionItem2: "Or remember or note down a 4-digit passphrase to export/import the keys securely.",
        memorablePassphrase: "If you use a memorable passphrase (e.g., the name of the platform like 'github'), it will be easier to recall. Only one of these (either the two keys or the 4-digit passphrase) is enough to securely manage your encrypted data.",
        textToEncryptDecrypt: "Text to Encrypt/Decrypt:",
        enterText: "Enter text...",
        extraKey1: "Extra Key 1:",
        enterKey1: "Enter key 1...",
        extraKey2: "Extra Key 2:",
        enterKey2: "Enter key 2...",
        encrypt: "Encrypt",
        decrypt: "Decrypt",
        keyExportImport: "Key Export/Import:",
        keysJSON: "Keys JSON...",
        passphrase: "4-digit Passphrase:",
        enterPassphrase: "Enter your passphrase...",
        exportTable: "Export Table",
        importTable: "Import Table",
        action: "Action",
        text: "Text",
        result: "Result",
        footer: "Beta Version 0.3.2 - July 2024",
        github: "GitHub"
    },
    tr: {
        title: "Gelişmiş Brute Şifreleme",
        encryptionDecryption: "Şifreleme ve Şifre Çözme",
        instructions: "Bu araç, iki anahtar kullanarak metin şifrelemenizi ve şifresini çözmenizi sağlar. Şunları yapabilirsiniz:",
        instructionItem1: "İki anahtarı (Ek Anahtar 1 ve Ek Anahtar 2) hatırlayın veya not alın,",
        instructionItem2: "Ya da anahtarları güvenli bir şekilde dışa aktarmak/içe aktarmak için 4 basamaklı bir parola hatırlayın veya not alın.",
        memorablePassphrase: "Hatırlanabilir bir parola kullanırsanız (örneğin, platformun adı gibi 'github'), hatırlamanız daha kolay olacaktır. Bunlardan sadece biri (ya iki anahtar ya da 4 basamaklı parola) şifrelenmiş verilerinizi güvenli bir şekilde yönetmek için yeterlidir.",
        textToEncryptDecrypt: "Şifrelenecek/Şifresi Çözülecek Metin:",
        enterText: "Metin girin...",
        extraKey1: "Ek Anahtar 1:",
        enterKey1: "Anahtar 1'i girin...",
        extraKey2: "Ek Anahtar 2:",
        enterKey2: "Anahtar 2'yi girin...",
        encrypt: "Şifrele",
        decrypt: "Şifre Çöz",
        keyExportImport: "Anahtar Dışa Aktarma/İçe Aktarma:",
        keysJSON: "Anahtarlar JSON...",
        passphrase: "4 Basamaklı Parola:",
        enterPassphrase: "Parolanızı girin...",
        exportTable: "Tabloyu Dışa Aktar",
        importTable: "Tabloyu İçe Aktar",
        action: "Eylem",
        text: "Metin",
        result: "Sonuç",
        footer: "Beta Sürüm 0.3.2 - Temmuz 2024",
        github: "GitHub"
    },
    ru: {
        title: "Продвинутое Брют Шифрование",
        encryptionDecryption: "Шифрование и Расшифровка",
        instructions: "Этот инструмент позволяет шифровать и расшифровывать текст с использованием двух ключей. Вы можете:",
        instructionItem1: "Запомнить или записать два ключа (Дополнительный Ключ 1 и Дополнительный Ключ 2),",
        instructionItem2: "Или запомнить или записать 4-значный пароль для безопасного экспорта/импорта ключей.",
        memorablePassphrase: "Если вы используете легко запоминающийся пароль (например, название платформы, как 'github'), его будет проще вспомнить. Достаточно одного из этих (либо двух ключей, либо 4-значного пароля) для безопасного управления вашими зашифрованными данными.",
        textToEncryptDecrypt: "Текст для Шифрования/Расшифровки:",
        enterText: "Введите текст...",
        extraKey1: "Дополнительный Ключ 1:",
        enterKey1: "Введите ключ 1...",
        extraKey2: "Дополнительный Ключ 2:",
        enterKey2: "Введите ключ 2...",
        encrypt: "Зашифровать",
        decrypt: "Расшифровать",
        keyExportImport: "Экспорт/Импорт Ключей:",
        keysJSON: "Ключи JSON...",
        passphrase: "4-значный Пароль:",
        enterPassphrase: "Введите ваш пароль...",
        exportTable: "Экспорт Таблицы",
        importTable: "Импорт Таблицы",
        action: "Действие",
        text: "Текст",
        result: "Результат",
        footer: "Бета Версия 0.3.2 - Июль 2024",
        github: "GitHub"
    },
    es: {
        title: "Cifrado Avanzado de Fuerza Bruta",
        encryptionDecryption: "Cifrado y Descifrado",
        instructions: "Esta herramienta le permite cifrar y descifrar texto usando dos claves. Usted puede:",
        instructionItem1: "Recordar o anotar las dos claves (Clave Extra 1 y Clave Extra 2),",
        instructionItem2: "O recordar o anotar una frase de contraseña de 4 dígitos para exportar/importar las claves de manera segura.",
        memorablePassphrase: "Si utiliza una frase de contraseña fácil de recordar (por ejemplo, el nombre de la plataforma como 'github'), será más fácil de recordar. Solo una de estas (ya sea las dos claves o la frase de contraseña de 4 dígitos) es suficiente para gestionar de manera segura sus datos cifrados.",
        textToEncryptDecrypt: "Texto para Cifrar/Descifrar:",
        enterText: "Introduzca el texto...",
        extraKey1: "Clave Extra 1:",
        enterKey1: "Introduzca la clave 1...",
        extraKey2: "Clave Extra 2:",
        enterKey2: "Introduzca la clave 2...",
        encrypt: "Cifrar",
        decrypt: "Descifrar",
        keyExportImport: "Exportación/Importación de Claves:",
        keysJSON: "Claves JSON...",
        passphrase: "Frase de Contraseña de 4 Dígitos:",
        enterPassphrase: "Introduzca su frase de contraseña...",
        exportTable: "Exportar Tabla",
        importTable: "Importar Tabla",
        action: "Acción",
        text: "Texto",
        result: "Resultado",
        footer: "Versión Beta 0.3.2 - Julio 2024",
        github: "GitHub"
    },
    de: {
        title: "Erweitertes Brute Cipher",
        encryptionDecryption: "Verschlüsselung und Entschlüsselung",
        instructions: "Dieses Tool ermöglicht es Ihnen, Text mit zwei Schlüsseln zu verschlüsseln und zu entschlüsseln. Sie können entweder:",
        instructionItem1: "Die beiden Schlüssel (Zusatzschlüssel 1 und Zusatzschlüssel 2) merken oder notieren,",
        instructionItem2: "Oder eine 4-stellige Passphrase merken oder notieren, um die Schlüssel sicher zu exportieren/importieren.",
        memorablePassphrase: "Wenn Sie eine einprägsame Passphrase verwenden (z.B. den Namen der Plattform wie 'github'), wird es einfacher zu merken sein. Nur eine dieser (entweder die beiden Schlüssel oder die 4-stellige Passphrase) reicht aus, um Ihre verschlüsselten Daten sicher zu verwalten.",
        textToEncryptDecrypt: "Text zum Verschlüsseln/Entschlüsseln:",
        enterText: "Text eingeben...",
        extraKey1: "Zusatzschlüssel 1:",
        enterKey1: "Schlüssel 1 eingeben...",
        extraKey2: "Zusatzschlüssel 2:",
        enterKey2: "Schlüssel 2 eingeben...",
        encrypt: "Verschlüsseln",
        decrypt: "Entschlüsseln",
        keyExportImport: "Schlüssel Export/Import:",
        keysJSON: "Schlüssel JSON...",
        passphrase: "4-stellige Passphrase:",
        enterPassphrase: "Passphrase eingeben...",
        exportTable: "Tabelle Exportieren",
        importTable: "Tabelle Importieren",
        action: "Aktion",
        text: "Text",
        result: "Ergebnis",
        footer: "Beta Version 0.3.2 - Juli 2024",
        github: "GitHub"
    },
    it: {
        title: "Cifratura Avanzata Brute",
        encryptionDecryption: "Cifratura e Decifratura",
        instructions: "Questo strumento consente di cifrare e decifrare il testo utilizzando due chiavi. Puoi:",
        instructionItem1: "Ricorda o annota le due chiavi (Chiave Extra 1 e Chiave Extra 2),",
        instructionItem2: "Oppure ricorda o annota una passphrase di 4 cifre per esportare/importare le chiavi in modo sicuro.",
        memorablePassphrase: "Se usi una passphrase memorabile (ad esempio, il nome della piattaforma come 'github'), sarà più facile da ricordare. Solo una di queste (o le due chiavi o la passphrase di 4 cifre) è sufficiente per gestire in modo sicuro i tuoi dati cifrati.",
        textToEncryptDecrypt: "Testo da Cifrare/Decifrare:",
        enterText: "Inserisci il testo...",
        extraKey1: "Chiave Extra 1:",
        enterKey1: "Inserisci la chiave 1...",
        extraKey2: "Chiave Extra 2:",
        enterKey2: "Inserisci la chiave 2...",
        encrypt: "Cifra",
        decrypt: "Decifra",
        keyExportImport: "Esportazione/Importazione Chiavi:",
        keysJSON: "Chiavi JSON...",
        passphrase: "Passphrase di 4 Cifre:",
        enterPassphrase: "Inserisci la tua passphrase...",
        exportTable: "Esporta Tabella",
        importTable: "Importa Tabella",
        action: "Azione",
        text: "Testo",
        result: "Risultato",
        footer: "Versione Beta 0.3.2 - Luglio 2024",
        github: "GitHub"
    },
    zh: {
        title: "高级暴力密码",
        encryptionDecryption: "加密和解密",
        instructions: "此工具允许您使用两个密钥加密和解密文本。您可以：",
        instructionItem1: "记住或记下这两个密钥（额外密钥1和额外密钥2），",
        instructionItem2: "或者记住或记下一个4位密码，以安全地导出/导入密钥。",
        memorablePassphrase: "如果您使用一个容易记住的密码（例如，平台的名称如'github'），它会更容易回忆。只需其中之一（两个密钥或4位密码）就足以安全地管理您的加密数据。",
        textToEncryptDecrypt: "要加密/解密的文本：",
        enterText: "输入文本...",
        extraKey1: "额外密钥1：",
        enterKey1: "输入密钥1...",
        extraKey2: "额外密钥2：",
        enterKey2: "输入密钥2...",
        encrypt: "加密",
        decrypt: "解密",
        keyExportImport: "密钥导出/导入：",
        keysJSON: "密钥JSON...",
        passphrase: "4位密码：",
        enterPassphrase: "输入您的密码...",
        exportTable: "导出表",
        importTable: "导入表",
        action: "操作",
        text: "文本",
        result: "结果",
        footer: "Beta版本 0.3.2 - 2024年7月",
        github: "GitHub"
    }
};
